# -*- coding: utf-8 -*-
"""TOT_Retrieval.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXHt48ShzF-ziC7KyJ4_NEcEEmbXHd86
"""

pip install pyserini

pip install faiss-cpu

!python -m pyserini.search.lucene --index /content/drive/MyDrive/TOT_Jsonl_index \
  --topics /content/drive/MyDrive/query.tsv \
  --output run.sample.txt \
  --bm25

import json


with open("/content/drive/MyDrive/query.txt","w") as f1:
  with open ("/content/drive/MyDrive/queries.jsonl","r") as f:
    for line in f:
      data=json.loads(line)
      #print(data)
      f1.write(data["id"])
      f1.write("\t")
      f1.write(data["text"])
      f1.write("\n")

f1.close()
f.close()

!python -m pyserini.eval.msmarco_passage_eval \
    tools/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt \
    runs/run.msmarco-passage.bm25tuned.txt

!python -m pyserini.search.lucene \
  --index indexes/lucene-index-msmarco-passage \
  --topics msmarco-passage-dev-subset \
  --output runs/run.msmarco-passage.bm25tuned.txt \
  --output-format msmarco \
  --hits 1000 \
  --bm25 --k1 0.82 --b 0.68 \
  --threads 4 --batch-size 16